# Generated by Django 5.0.4 on 2024-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_add_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='location',
            field=models.CharField(choices=[('nikol', 'Nikol'), ('viratnagar', 'Viratnagar'), ('new india-colony', 'New India-colony'), ('naroda', 'Naroda'), ('bapunagar', 'Bapunagar')], default='', max_length=20),
        ),
    ]
