# Generated by Django 5.0.4 on 2024-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_add_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.EmailField(blank=True, max_length=70)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
