# Generated by Django 5.0.4 on 2024-05-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_contact_lname_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
